# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - run: ./earthly +publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
